version: '3'
services:

  zammad-railsserver:
    image: 1drop/zammad:zammad-211
    volumes:
      - data-zammad:/home/zammad
    depends_on:
      - zammad-elasticsearch
      - zammad-postgresql
    labels:
      io.rancher.container.pull_image: always
    restart: always
    command: ["zammad-railsserver"]

  zammad-scheduler:
    image: 1drop/zammad:zammad-211
    volumes:
      - data-zammad:/home/zammad
    depends_on:
      - zammad
      - zammad-elasticsearch
      - zammad-postgresql
    labels:
      io.rancher.container.pull_image: always
    restart: always
    command: ["zammad-scheduler"]

  zammad-websocket:
    image: 1drop/zammad:zammad-211
    volumes:
      - data-zammad:/home/zammad
    depends_on:
      - zammad-elasticsearch
      - zammad-postgresql
    labels:
      io.rancher.container.pull_image: always
    restart: always
    command: ["zammad-websocket"]

  zammad-nginx:
    image: 1drop/zammad:nginx
    volumes:
      - data-zammad:/home/zammad
    environment:
      - VIRTUAL_HOST=zammad.docker
    links:
      - zammad-railsserver
      - zammad-websocket
    restart: always
    labels:
      io.rancher.container.pull_image: always

  zammad-postgresql:
    image: postgres:9.6
    restart: always
    volumes:
      - data-postgres:/var/lib/postgres/data
    labels:
      io.rancher.container.pull_image: always

  zammad-elasticsearch:
    image: 1drop/zammad:elasticsearch
    restart: always
    volumes:
      - data-elasticsearch:/usr/share/elasticsearch/data
    labels:
      io.rancher.container.pull_image: always


volumes:

  data-zammad:
    driver: local

  data-elasticsearch:
    driver: local

  data-postgres:
    driver: local
