version: '2'
services:
  zammad:
    image: 1drop/zammad:zammad
    stdin_open: true
    volumes:
    - data-zammad:/home/zammad
    tty: true
    links:
    - postgresql:postgresql
    - elasticsearch:elasticsearch
    depends_on: 
    - postgresql
    - elasticsearch
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: host=git.1drop.de
  postgresql:
    image: postgres
    stdin_open: true
    volumes:
    - /opt/zammad/pgsql:/var/lib/postgresql/data
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: host=git.1drop.de
  nginx:
    image: 1drop/zammad:nginx
    stdin_open: true
    volumes:
      - data-zammad:/home/zammad
    depends_on: 
    - zammad
    tty: true
    links:
    - zammad:zammad
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: host=git.1drop.de
  elasticsearch:
    image: 1drop/zammad:elasticsearch
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: host=git.1drop.de
volumes:
  data-zammad:
    driver: local
