version: '3'
services:

  zammad:
    image: 1drop/zammad:zammad-211
    volumes:
      - data-zammad:/home/zammad
    depends_on:
      - zammad-postgresql
      - zammad-elasticsearch
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.start_once: 'true'
    restart: on-failure

  zammad-railsserver:
    image: 1drop/zammad:zammad-211
    volumes:
      - data-zammad:/home/zammad
    depends_on:
      - zammad
      - zammad-elasticsearch
      - zammad-postgresql
    labels:
      io.rancher.container.pull_image: always
    restart: always
    command: ["zammad-railsserver"]

  zammad-scheduler:
    image: 1drop/zammad:zammad-211
    volumes:
      - data-zammad:/home/zammad
    depends_on:
      - zammad
      - zammad-elasticsearch
      - zammad-postgresql
    labels:
      io.rancher.container.pull_image: always
    restart: always
    command: ["zammad-scheduler"]

  zammad-websocket:
    image: 1drop/zammad:zammad-211
    volumes:
      - data-zammad:/home/zammad
    depends_on:
      - zammad
      - zammad-elasticsearch
      - zammad-postgresql
    labels:
      io.rancher.container.pull_image: always
    restart: always
    command: ["zammad-websocket"]

  zammad-backup:
    image: 1drop/zammad:zammad-211
    volumes:
      - data-zammad:/home/zammad
      - backup-zammad:/var/tmp/zammad
    depends_on:
      - zammad
      - zammad-elasticsearch
      - zammad-postgresql
    labels:
      io.rancher.container.pull_image: always
    restart: always
    command: ["zammad-backup"]

  zammad-nginx:
    image: 1drop/zammad:nginx
    volumes:
      - data-zammad:/home/zammad
    environment:
      - VIRTUAL_HOST=zammad.docker
    depends_on:
      - zammad-railsserver
      - zammad-websocket
    labels:
      io.rancher.container.pull_image: always

  zammad-postgresql:
    image: postgres:9.6
    volumes:
      - data-postgres:/var/lib/postgres/data
    labels:
      io.rancher.container.pull_image: always

  zammad-elasticsearch:
    image: 1drop/zammad:elasticsearch
    restart: always
    volumes:
      - data-elasticsearch:/usr/share/elasticsearch/data
    labels:
      io.rancher.container.pull_image: always


volumes:

  data-zammad:
    driver: local

  data-elasticsearch:
    driver: local

  backup-zammad:
    driver: local

  data-postgres:
    driver: local
